In [1]:
import os

In [2]:
%pwd

'c:\\Users\\xaris\\Desktop\\SQL\\Teen Phone Addiction Project\\Teen_Phone_Addiction\\research'

In [3]:
os.chdir(r"C:\Users\xaris\Desktop\SQL\Teen Phone Addiction Project\\Teen_Phone_Addiction")

In [4]:
%pwd

'C:\\Users\\xaris\\Desktop\\SQL\\Teen Phone Addiction Project\\Teen_Phone_Addiction'

In [11]:
import pandas as pd
df = pd.read_csv(r"artifacts\data_ingestion\extracted_data\teen_phone_addiction_dataset.csv")
df.head()

,ID,Name,Age,Gender,Location,School_Grade,Daily_Usage_Hours,Sleep_Hours,Academic_Performance,Social_Interactions,...,Screen_Time_Before_Bed,Phone_Checks_Per_Day,Apps_Used_Daily,Time_on_Social_Media,Time_on_Gaming,Time_on_Education,Phone_Usage_Purpose,Family_Communication,Weekend_Usage_Hours,Addiction_Level
0,1,Shannon Francis,13,Female,Hansonfort,9th,4.0,6.1,78,5,...,1.4,86,19,3.6,1.7,1.2,Browsing,4,8.7,10.0
1,2,Scott Rodriguez,17,Female,Theodorefort,7th,5.5,6.5,70,5,...,0.9,96,9,1.1,4.0,1.8,Browsing,2,5.3,10.0
2,3,Adrian Knox,13,Other,Lindseystad,11th,5.8,5.5,93,8,...,0.5,137,8,0.3,1.5,0.4,Education,6,5.7,9.2
3,4,Brittany Hamilton,18,Female,West Anthony,12th,3.1,3.9,78,8,...,1.4,128,7,3.1,1.6,0.8,Social Media,8,3.0,9.8
4,5,Steven Smith,14,Other,Port Lindsaystad,9th,2.5,6.7,56,4,...,1.0,96,20,2.6,0.9,1.1,Gaming,10,3.7,8.6

In [12]:
df.columns

Index(['ID', 'Name', 'Age', 'Gender', 'Location', 'School_Grade',
       'Daily_Usage_Hours', 'Sleep_Hours', 'Academic_Performance',
       'Social_Interactions', 'Exercise_Hours', 'Anxiety_Level',
       'Depression_Level', 'Self_Esteem', 'Parental_Control',
       'Screen_Time_Before_Bed', 'Phone_Checks_Per_Day', 'Apps_Used_Daily',
       'Time_on_Social_Media', 'Time_on_Gaming', 'Time_on_Education',
       'Phone_Usage_Purpose', 'Family_Communication', 'Weekend_Usage_Hours',
       'Addiction_Level'],
      dtype='object')

In [13]:
df.shape

(3000, 25)

In [15]:
pd.set_option('display.max_columns', None)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 25 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ID                      3000 non-null   int64
 1   Name                    3000 non-null   object
 2   Age                     3000 non-null   int64
 3   Gender                  3000 non-null   object
 4   Location                3000 non-null   object
 5   School_Grade            3000 non-null   object
 6   Daily_Usage_Hours       3000 non-null   float64
 7   Sleep_Hours             3000 non-null   float64
 8   Academic_Performance    3000 non-null   int64
 9   Social_Interactions     3000 non-null   int64
 10  Exercise_Hours          3000 non-null   float64
 11  Anxiety_Level           3000 non-null   int64
 12  Depression_Level        3000 non-null   int64
 13  Self_Esteem             3000 non-null   int64
 14  Parental_Control        3000 non-null   int64
 15  Screen_Time_Before_Bed  3000 non-null   float64
 16  Phone_Checks_Per_Day    3000 non-null   int64
 17  Apps_Used_Daily         3000 non-null   int64
 18  Time_on_Social_Media    3000 non-null   float64
 19  Time_on_Gaming          3000 non-null   float64
 20  Time_on_Education       3000 non-null   float64
 21  Phone_Usage_Purpose     3000 non-null   object
 22  Family_Communication    3000 non-null   int64
 23  Weekend_Usage_Hours     3000 non-null   float64
 24  Addiction_Level         3000 non-null   float64
dtypes: float64(9), int64(11), object(5)
memory usage: 586.1+ KB

In [ ]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
ID,3000.0,1500.500000,866.169729,1.0,750.75,1500.5,2250.25,3000.0
Age,3000.0,15.969667,1.989489,13.0,14.00,16.0,18.00,19.0
Daily_Usage_Hours,3000.0,5.020667,1.956501,0.0,3.70,5.0,6.40,11.5
Sleep_Hours,3000.0,6.489767,1.490713,3.0,5.50,6.5,7.50,10.0
Academic_Performance,3000.0,74.947333,14.684156,50.0,62.00,75.0,88.00,100.0
Social_Interactions,3000.0,5.097667,3.139333,0.0,2.00,5.0,8.00,10.0
Exercise_Hours,3000.0,1.040667,0.734620,0.0,0.50,1.0,1.50,4.0
Anxiety_Level,3000.0,5.590000,2.890678,1.0,3.00,6.0,8.00,10.0
Depression_Level,3000.0,5.460333,2.871557,1.0,3.00,5.0,8.00,10.0
Self_Esteem,3000.0,5.546333,2.860754,1.0,3.00,6.0,8.00,10.0
Parental_Control,3000.0,0.507333,0.500030,0.0,0.00,1.0,1.00,1.0
Screen_Time_Before_Bed,3000.0,1.006733,0.492878,0.0,0.70,1.0,1.40,2.6
Phone_Checks_Per_Day,3000.0,83.093000,37.747044,20.0,51.00,82.0,115.25,150.0
Apps_Used_Daily,3000.0,12.609333,4.611486,5.0,9.00,13.0,17.00,20.0
Time_on_Social_Media,3000.0,2.499233,0.988201,0.0,1.80,2.5,3.20,5.0
Time_on_Gaming,3000.0,1.525267,0.932701,0.0,0.80,1.5,2.20,4.0
Time_on_Education,3000.0,1.016333,0.648341,0.0,0.50,1.0,1.50,3.0
Family_Communication,3000.0,5.459667,2.864572,1.0,3.00,5.0,8.00,10.0
Weekend_Usage_Hours,3000.0,6.015100,2.014776,0.0,4.70,6.0,7.40,14.0
Addiction_Level,3000.0,8.881900,1.609598,1.0,8.00,10.0,10.00,10.0

In [17]:
df.isnull().sum()

ID                        0
Name                      0
Age                       0
Gender                    0
Location                  0
School_Grade              0
Daily_Usage_Hours         0
Sleep_Hours               0
Academic_Performance      0
Social_Interactions       0
Exercise_Hours            0
Anxiety_Level             0
Depression_Level          0
Self_Esteem               0
Parental_Control          0
Screen_Time_Before_Bed    0
Phone_Checks_Per_Day      0
Apps_Used_Daily           0
Time_on_Social_Media      0
Time_on_Gaming            0
Time_on_Education         0
Phone_Usage_Purpose       0
Family_Communication      0
Weekend_Usage_Hours       0
Addiction_Level           0
dtype: int64

In [ ]:
from pathlib import Path
from dataclasses import dataclass

@dataclass(frozen=True)
class DataValidationConfig:
    root_dir: Path
    unzip_data_dir: Path
    STATUS_FILE : str
    all_schema : dict

In [20]:
from Teen_Phone_Addiction.constants import *
from Teen_Phone_Addiction.utils.common import read_yaml, create_directories

In [27]:
class ConfigurationManager:
    def __init__(
        self, 
        config_file_path = CONFIG_FILE_PATH,
        params_file_path = PARAMS_FILE_PATH,
        schema_file_path = SCHEMA_FILE_PATH): 

        self.config = read_yaml(config_file_path)
        self.params = read_yaml(params_file_path)
        self.schema = read_yaml(schema_file_path)

        create_directories([self.config.artifacts_root])

    def get_data_validation_config(self) -> DataValidationConfig:
        config = self.config.data_validation
        schema = self.schema.COLUMNS 

        create_directories([config.root_dir])
        
        data_validation_config = DataValidationConfig(
            root_dir=config.root_dir,
            STATUS_FILE=config.STATUS_FILE,
            unzip_data_dir=config.unzip_data_dir,
            all_schema=schema
        )
        
        return data_validation_config

In [37]:
import os
from Teen_Phone_Addiction import logger

In [29]:
class DataValidation:
    def __init__(self, config: DataValidationConfig):
        self.config = config


    def validate_data(self):
        try:
            validation_status = None

            df = pd.read_csv(self.config.unzip_data_dir)
            all_columns = list(df.columns)

            all_schema = self.config.all_schema.keys()

            for column in all_columns:
                if column not in all_schema:
                    validation_status = False
                    with open(self.config.STATUS_FILE, 'w') as f:
                        f.write(f"Validation Status: {validation_status}\n")
                
                else:
                    validation_status = True
                    with open(self.config.STATUS_FILE, 'w') as f:
                        f.write(f"Validation Status: {validation_status}\n")

                return validation_status
                    
        except Exception as e:
            raise e

In [38]:
try:
        config = ConfigurationManager()
        data_validation_config = config.get_data_validation_config()
        data_validation = DataValidation(config=data_validation_config)
        data_validation.validate_data()
except Exception as e:
    raise e

[2025-08-06 17:32:07,096: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-08-06 17:32:07,102: INFO: common: yaml file: params.yaml loaded successfully]
[2025-08-06 17:32:07,125: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-08-06 17:32:07,128: INFO: common: created directory at: artifacts]
[2025-08-06 17:32:07,131: INFO: common: created directory at: artifacts/data_validation]